### ISSUE TITLE
Namespace typo and invalid Exception load

### ISSUE THREAD

**Issue by magik092** [web-com-pl/amazon-mws-orders#1]
On GetMatchingProductForIdResponse while got error like `You can have no more than 5 elements in ID list` Api trying to load `AmazonException` but extend `Exception` is invalid (missing `\` at beginning).
Namespace of `AmazonException` is invalid too: `namespace Webcom\MarketPlaceWebService;` => `namespace Webcom\MarketPlaceWebServiceProducts;`

**Comment by magik092** [comment]
@Radeq, you can do your job 😃

**Comment by magik092** [comment]
Fixed in #cd88abbbc17e7cc9425cb5ad88eeb0579d2aea80

**Comment by Radeq** [comment]
Fixed in cd88abbbc17e7cc9425cb5ad88eeb0579d2aea80
